### ISSUE TITLE
Link to Building Secure and Reliable Systems is broken

### ISSUE THREAD

**Issue by mzraly** [andrealmar/sre-university#7]
The link to the Building Secure and Reliable Systems book is broken.  This one works:
https://landing.google.com/sre/resources/foundationsandprinciples/srs-book/

**Comment by andrealmar** [comment]
Hi @mzraly thanks for pointing it out. Can you please send a PR to fix the broken link ?

**Comment by ari-hacks** [comment]
@andrealmar I put in a PR for this. Great list of resources, thanks!

**Comment by andrealmar** [comment]
thanks @ari-hacks
